const mockUser = {
  login: "tagaca19e",
  id: 56732160,
  node_id: "MDQ6VXNlcjU2NzMyMTYw",
  avatar_url:
    "https://avatars.githubusercontent.com/u/85138779?s=400&u=1670811a1d305a0d675464d0a960a304ab35d3ec&v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/tagaca19e",
  html_url: "https://github.com/tagaca19e",
  followers_url: "https://api.github.com/users/tagaca19e/followers",
  following_url:
    "https://api.github.com/users/tagaca19e/following{/other_user}",
  gists_url: "https://api.github.com/users/tagaca19e/gists{/gist_id}",
  starred_url: "https://api.github.com/users/tagaca19e/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/tagaca19e/subscriptions",
  organizations_url: "https://api.github.com/users/tagaca19e/orgs",
  repos_url: "https://api.github.com/users/tagaca19e/repos",
  events_url: "https://api.github.com/users/tagaca19e/events{/privacy}",
  received_events_url: "https://api.github.com/users/tagaca19e/received_events",
  type: "User",
  site_admin: false,
  name: "thilak reddy",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: "thilak_reddy_ch",
  public_repos: 3,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2019-10-18T15:00:43Z",
  updated_at: "2020-12-28T09:38:38Z",
};

export default mockUser;
